[package]
name = "meeseeks_html5ever_nif"
version = "0.13.1"
authors = ["Mischov <mmischov@gmail.com>"]

[lib]
name = "meeseeks_html5ever_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22"

html5ever = "0.22"
xml5ever = "0.12"
markup5ever = "0.7"
tendril = "0.4"
